name: Main push
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Job Main done"'
  job-a:
    needs: [first]
    uses: ./.github/workflows/reused-workflow.yml
    with:
      baseURL: https://${{ needs.setup.outputs.branch_name }}.github.com
